/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#19101c",
        "surface-dim": "#19101c",
        "secondary-container": "#00eefc",
        "surface-variant": "#3c313e",
        "primary-container": "#bd00ff",
        "secondary": "#d3fbff",
        "on-secondary-container": "#00686f",
        "surface-container-lowest": "#130b16",
        "surface-container-high": "#302733",
        "error-container": "#93000a",
        "surface-container-low": "#211824",
        "error": "#ffb4ab",
        "on-surface": "#eeddee",
        "on-secondary": "#00363a",
        "on-primary": "#520071",
        "on-primary-fixed": "#320047",
        "on-error": "#690005",
        "primary-fixed": "#f8d8ff",
        "on-background": "#eeddee",
        "on-surface-variant": "#d4c0d7",
        "on-primary-container": "#ffffff",
        "surface-container-highest": "#3c313e",
        "tertiary": "#ffb1c3",
        "tertiary-container": "#e7006e",
        "outline-variant": "#514255",
        "background": "#19101c",
        "primary": "#ecb2ff",
        "surface-container": "#261c28",
        "surface-bright": "#403643",
        "outline": "#9d8ba0",
        "primary-fixed-dim": "#ecb2ff",
        "on-tertiary-container": "#ffffff",
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Bebas Neue", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg":    ["Plus Jakarta Sans", "sans-serif"],
        "body-md":    ["Plus Jakarta Sans", "sans-serif"],
        "headline-md":["Bebas Neue", "sans-serif"],
        "display-xl": ["Bebas Neue", "sans-serif"],
        sans: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "48px", letterSpacing: "0.03em", fontWeight: "400" }],
        "label-bold":  ["14px", { lineHeight: "16px", fontWeight: "700" }],
        "body-lg":     ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md":     ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "32px", letterSpacing: "0.04em", fontWeight: "400" }],
        "display-xl":  ["80px", { lineHeight: "80px", letterSpacing: "0.02em", fontWeight: "400" }],
      },
      maxWidth: { "container-max": "1280px" },
    },
  },
  plugins: [],
}
